package vault

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/vadymdidenkolab/docket/internal/project"
)

// Boards a vault ships with.
const (
	BoardFile   = "boards/board.base"
	BacklogFile = "boards/backlog.base"
	MineFile    = "boards/my-tasks.base"
)

// WriteBoards regenerates the Bases views from the vault's configuration.
//
// A board selects tasks by naming the project folders, so adding a project
// means rewriting the boards. The alternative — a filter that recognises a task
// by the properties it carries — would quietly include pages that happen to
// have a status, and quietly exclude tasks in a project nobody remembered to
// add. Naming the projects is explicit, and `docket check` reports a project no
// board mentions.
func WriteBoards(root string, c *project.Config) ([]string, error) {
	boards := map[string]string{
		BoardFile:   boardBase(c),
		BacklogFile: backlogBase(c),
		MineFile:    mineBase(c),
	}

	if err := os.MkdirAll(filepath.Join(root, BoardsDir), 0o755); err != nil {
		return nil, err
	}

	var written []string
	for rel, body := range boards {
		if err := os.WriteFile(filepath.Join(root, filepath.FromSlash(rel)), []byte(body), 0o644); err != nil {
			return nil, err
		}
		written = append(written, rel)
	}
	return written, nil
}

// InProjects is the filter clause that selects every task in the vault.
func InProjects(c *project.Config) string {
	var lines []string
	for _, key := range c.ProjectKeys() {
		lines = append(lines, fmt.Sprintf("      - file.inFolder(%q)", key))
	}
	return strings.Join(lines, "\n")
}

// Two details here were found by opening this in Obsidian rather than by
// reading its documentation, which is wrong about both. Checked against
// Obsidian 1.13.7 — see IGL-12.
//
// `groupBy` needs `direction` as well as `property`. Without it the whole file
// is refused with "groupBy must be of type object", which is true of the value
// and is not the reason: the parser wants both keys and says neither.
//
// A property in `properties:` is written qualified — `note.title`, not `title`.
// The published example uses the bare form; the bare form silently does
// nothing, because the key is matched against the same qualified id that
// `order` uses.
func boardBase(c *project.Config) string {
	return `# Regenerated by docket. Projects are named explicitly; run
# "docket project add" to add one and rewrite these filters.
filters:
  and:
    - or:
` + InProjects(c) + `
    - 'note.status_category != "done"'
properties:
  note.title:
    displayName: Title
  note.assignee:
    displayName: Assignee
  note.priority:
    displayName: Priority
  note.tags:
    displayName: Tags
views:
  - type: cards
    name: Board
    groupBy:
      property: note.status
      direction: ASC
    order:
      - note.title
      - note.assignee
      - note.priority
      - note.labels
      - note.tags
`
}

func backlogBase(c *project.Config) string {
	return `# Regenerated by docket.
filters:
  and:
    - or:
` + InProjects(c) + `
    - 'note.status_category == "todo"'
` + notSubtasks(c) + `properties:
  note.key:
    displayName: Key
  note.title:
    displayName: Title
  note.type:
    displayName: Type
  note.priority:
    displayName: Priority
  note.parent:
    displayName: Parent
  note.labels:
    displayName: Labels
views:
  - type: table
    name: Backlog
    order:
      - note.key
      - note.title
      - note.type
      - note.priority
      - note.parent
      - note.labels
`
}

func mineBase(c *project.Config) string {
	return `# Regenerated by docket. Change the assignee below to your own handle.
filters:
  and:
    - or:
` + InProjects(c) + `
    - 'note.assignee == "agent/claude"'
    - 'note.status_category != "done"'
properties:
  note.key:
    displayName: Key
  note.title:
    displayName: Title
  note.status:
    displayName: Status
  note.priority:
    displayName: Priority
  note.updated:
    displayName: Updated
views:
  - type: table
    name: My tasks
    order:
      - note.key
      - note.title
      - note.status
      - note.priority
      - note.updated
`
}

// notSubtasks keeps work that lives inside a task out of the backlog.
//
// A sub-task is not a thing to schedule; a backlog listing it beside the task
// it belongs to counts the same work twice. Jira does this by hierarchy level
// and so does this — but only for a vault that has said what its levels are.
func notSubtasks(c *project.Config) string {
	var out strings.Builder
	for _, t := range c.Types {
		if t.Level < project.LevelStandard {
			fmt.Fprintf(&out, "    - 'note.type != %q'\n", t.Name)
		}
	}
	return out.String()
}
