package vault

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/vadymdidenkolab/docket/internal/project"
)

// Boards a vault ships with.
const (
	BoardFile   = "boards/board.base"
	BacklogFile = "boards/backlog.base"
	MineFile    = "boards/my-tasks.base"
	// SprintFile is the board for the sprint. Written only by a vault that runs
	// sprints, because a board that is always empty is a board that teaches
	// people the boards are empty.
	SprintFile = "boards/sprint.base"
)

// WriteBoards regenerates the Bases views from the vault's configuration.
//
// A board selects tasks by naming the project folders, so adding a project
// means rewriting the boards. The alternative — a filter that recognises a task
// by the properties it carries — would quietly include pages that happen to
// have a status, and quietly exclude tasks in a project nobody remembered to
// add. Naming the projects is explicit, and `docket check` reports a project no
// board mentions.
func WriteBoards(root string, c *project.Config) ([]string, error) {
	if err := os.MkdirAll(filepath.Join(root, BoardsDir), 0o755); err != nil {
		return nil, err
	}

	// Whether this vault runs sprints is a fact about its files, not about its
	// configuration — a sprint is a page, and having written one is how a vault
	// says it works that way.
	sprints, err := Sprints(root)
	if err != nil {
		sprints = nil
	}

	var written []string
	for rel, body := range GeneratedIn(c, len(sprints) > 0) {
		if err := os.WriteFile(filepath.Join(root, filepath.FromSlash(rel)), []byte(body), 0o644); err != nil {
			return nil, err
		}
		written = append(written, rel)
	}
	return written, nil
}

// Generated is what each board file should contain, given the configuration.
//
// The boards are derived from docket.yaml and nothing else, so there is always a
// right answer for what is in them — which is why `docket check --fix` may
// rewrite one that has drifted. See Marker.
func Generated(c *project.Config) map[string]string {
	return map[string]string{
		BoardFile:   boardBase(c),
		BacklogFile: backlogBase(c),
		MineFile:    mineBase(c),
	}
}

// GeneratedIn is Generated plus the boards that depend on what is in the vault
// rather than only on its configuration.
//
// The sprint board is the one: a vault with no sprint pages should not get a
// board of nothing, and whether it has any is a fact about the files. Passed in
// rather than read here, because the caller has already walked them.
func GeneratedIn(c *project.Config, sprints bool) map[string]string {
	out := Generated(c)
	if sprints {
		out[SprintFile] = sprintBase(c)
	}
	return out
}

// sprintBase is the board of the sprint, in Obsidian, with no tool running.
//
// This is the reason a task carries `sprint:` rather than the sprint page
// carrying a list: Bases filters on a property of the note it is drawing, so a
// list on the page would be invisible here. See purpose §5.
//
// It shows every sprint rather than only the running one, grouped by sprint,
// because Bases cannot ask what today is. Newest first is what DESC gives on a
// name that ends in a number — which is a real reason to number sprints.
func sprintBase(c *project.Config) string {
	return `# Regenerated by docket. The sprint board exists because a task carries
# its sprint as a property: Bases can only filter on what the note itself says.
filters:
  and:
    - or:
` + InProjects(c) + `
    - 'note.sprint'
formulas:
  stage: '` + stageFormula(c) + `'
properties:
  formula.stage:
    displayName: Stage
  note.sprint:
    displayName: Sprint
  note.title:
    displayName: Title
  note.estimate:
    displayName: Size
  note.assignee:
    displayName: Assignee
views:
  - type: cards
    name: Sprint
    groupBy:
      property: note.sprint
      direction: DESC
    order:
      - note.title
      - formula.stage
      - note.estimate
      - note.assignee
  - type: table
    name: By stage
    groupBy:
      property: formula.stage
      direction: ASC
    order:
      - note.key
      - note.title
      - note.sprint
      - note.estimate
      - note.assignee
`
}

// Marker is the first line of a board docket generated.
//
// Delete it and the file is yours: nothing regenerates it and `docket check`
// stops having an opinion about what is in it. A board is a Bases view like any
// other, and a vault that wants a different one should not have to fight the
// tool for it.
const Marker = "# Regenerated by docket"

// InProjects is the filter clause that selects every task in the vault.
func InProjects(c *project.Config) string {
	var lines []string
	for _, key := range c.ProjectKeys() {
		lines = append(lines, fmt.Sprintf("      - file.inFolder(%q)", key))
	}
	return strings.Join(lines, "\n")
}

// Two details here were found by opening this in Obsidian rather than by
// reading its documentation, which is wrong about both. Checked against
// Obsidian 1.13.7 — see IGL-12.
//
// `groupBy` needs `direction` as well as `property`. Without it the whole file
// is refused with "groupBy must be of type object", which is true of the value
// and is not the reason: the parser wants both keys and says neither.
//
// A property in `properties:` is written qualified — `note.title`, not `title`.
// The published example uses the bare form; the bare form silently does
// nothing, because the key is matched against the same qualified id that
// `order` uses.
func boardBase(c *project.Config) string {
	return `# Regenerated by docket. Projects are named explicitly; run
# "docket project add" to add one and rewrite these filters.
filters:
  and:
    - or:
` + InProjects(c) + `
    - 'note.status_category != "done"'
formulas:
  stage: '` + stageFormula(c) + `'
properties:
  formula.stage:
    displayName: Stage
  note.title:
    displayName: Title
  note.assignee:
    displayName: Assignee
  note.priority:
    displayName: Priority
  note.estimate:
    displayName: Size
  note.tags:
    displayName: Tags
views:
  - type: cards
    name: Board
    groupBy:
      property: formula.stage
      direction: ASC
    order:
      - note.title
      - note.assignee
      - note.priority
      - note.estimate
      - note.labels
      - note.tags
`
}

// stageFormula numbers each status so that Obsidian draws the columns in the
// order docket.yaml lists them.
//
// Bases groups by a value and sorts the groups ASC or DESC — there is no third
// option, and no way to hand it an order. Grouping by the status itself
// therefore sorts the columns alphabetically, which for a workflow means
// nonsense: an eight-stage pipeline came out with Business Review first and
// Discovery second. It looks almost right on a three-column vault, which is why
// it survived until a vault with a real pipeline was opened.
//
// So the board groups by a formula that puts the stage number in front of the
// name. The number is visible in the column heading, which is the cost, and it
// is also the answer to "which stage is this" — the same thing a pipeline board
// numbers its columns for.
func stageFormula(c *project.Config) string {
	expr := `""`
	for i := len(c.Statuses) - 1; i >= 0; i-- {
		name := basesString(c.Statuses[i].Name)
		expr = fmt.Sprintf(`if(note.status == %s, %s, %s)`,
			name, basesString(fmt.Sprintf("%d. %s", i+1, c.Statuses[i].Name)), expr)
	}
	return expr
}

// basesString quotes a value for a Bases formula, which is inside a
// single-quoted YAML scalar. A double quote is the string delimiter and a
// single quote ends the scalar, so both have to go.
func basesString(v string) string {
	v = strings.ReplaceAll(v, `"`, "")
	v = strings.ReplaceAll(v, "'", "")
	return `"` + v + `"`
}

func backlogBase(c *project.Config) string {
	return `# Regenerated by docket.
filters:
  and:
    - or:
` + InProjects(c) + `
    - 'note.status_category == "todo"'
` + notSubtasks(c) + `properties:
  note.key:
    displayName: Key
  note.title:
    displayName: Title
  note.type:
    displayName: Type
  note.priority:
    displayName: Priority
  note.parent:
    displayName: Parent
  note.labels:
    displayName: Labels
views:
  - type: table
    name: Backlog
    order:
      - note.key
      - note.title
      - note.type
      - note.priority
      - note.parent
      - note.labels
`
}

func mineBase(c *project.Config) string {
	return `# Regenerated by docket. Change the assignee below to your own handle.
filters:
  and:
    - or:
` + InProjects(c) + `
    - 'note.assignee == "agent/claude"'
    - 'note.status_category != "done"'
properties:
  note.key:
    displayName: Key
  note.title:
    displayName: Title
  note.status:
    displayName: Status
  note.priority:
    displayName: Priority
  note.updated:
    displayName: Updated
views:
  - type: table
    name: My tasks
    order:
      - note.key
      - note.title
      - note.status
      - note.priority
      - note.updated
`
}

// notSubtasks keeps work that lives inside a task out of the backlog.
//
// A sub-task is not a thing to schedule; a backlog listing it beside the task
// it belongs to counts the same work twice. Jira does this by hierarchy level
// and so does this — but only for a vault that has said what its levels are.
func notSubtasks(c *project.Config) string {
	var out strings.Builder
	for _, t := range c.Types {
		if t.Level < project.LevelStandard {
			fmt.Fprintf(&out, "    - 'note.type != %q'\n", t.Name)
		}
	}
	return out.String()
}
