#!/bin/sh
#
# Generate the Homebrew formula and the Scoop manifest for a published tag.
#
#   script/packaging.sh v0.6.0 OUTPUT_DIR
#
# Both are generated from the checksums the release itself publishes, so a
# package manager can never be pointed at a file the release did not build.

set -eu

tag=${1:?usage: packaging.sh TAG OUTPUT_DIR}
out=${2:?usage: packaging.sh TAG OUTPUT_DIR}
repo=didenkolab/docket
base="https://github.com/$repo/releases/download/$tag"
bare=${tag#v}

sums=$(mktemp)
trap 'rm -f "$sums"' EXIT INT TERM
curl -fsSL "$base/checksums.txt" -o "$sums"

sum() {
  value=$(grep " $1\$" "$sums" | cut -d' ' -f1)
  [ -n "$value" ] || { echo "no checksum for $1" >&2; exit 1; }
  printf '%s' "$value"
}

mkdir -p "$out/Formula" "$out/bucket"

cat > "$out/Formula/docket.rb" <<RUBY
# Generated by script/packaging.sh from the checksums $tag publishes.
class Docket < Formula
  desc "Git and Obsidian as one task tracker: a task is a Markdown file"
  homepage "https://github.com/$repo"
  license "MIT"

  on_macos do
    on_arm do
      url "$base/docket_${tag}_darwin_arm64.tar.gz"
      sha256 "$(sum "docket_${tag}_darwin_arm64.tar.gz")"
    end
    on_intel do
      url "$base/docket_${tag}_darwin_amd64.tar.gz"
      sha256 "$(sum "docket_${tag}_darwin_amd64.tar.gz")"
    end
  end

  on_linux do
    on_arm do
      url "$base/docket_${tag}_linux_arm64.tar.gz"
      sha256 "$(sum "docket_${tag}_linux_arm64.tar.gz")"
    end
    on_intel do
      url "$base/docket_${tag}_linux_amd64.tar.gz"
      sha256 "$(sum "docket_${tag}_linux_amd64.tar.gz")"
    end
  end

  def install
    bin.install "docket"
  end

  test do
    assert_match "$tag", shell_output("#{bin}/docket --version")
  end
end
RUBY

cat > "$out/bucket/docket.json" <<JSON
{
    "version": "$bare",
    "description": "Git and Obsidian as one task tracker: a task is a Markdown file, every move is a commit.",
    "homepage": "https://github.com/$repo",
    "license": "MIT",
    "architecture": {
        "64bit": {
            "url": "$base/docket_${tag}_windows_amd64.zip",
            "hash": "$(sum "docket_${tag}_windows_amd64.zip")",
            "extract_dir": "docket_${tag}_windows_amd64"
        },
        "arm64": {
            "url": "$base/docket_${tag}_windows_arm64.zip",
            "hash": "$(sum "docket_${tag}_windows_arm64.zip")",
            "extract_dir": "docket_${tag}_windows_arm64"
        }
    },
    "bin": "docket.exe",
    "checkver": {
        "github": "https://github.com/$repo"
    },
    "autoupdate": {
        "architecture": {
            "64bit": {
                "url": "https://github.com/$repo/releases/download/v\$version/docket_v\$version_windows_amd64.zip",
                "extract_dir": "docket_v\$version_windows_amd64"
            },
            "arm64": {
                "url": "https://github.com/$repo/releases/download/v\$version/docket_v\$version_windows_arm64.zip",
                "extract_dir": "docket_v\$version_windows_arm64"
            }
        },
        "hash": {
            "url": "https://github.com/$repo/releases/download/v\$version/checksums.txt"
        }
    }
}
JSON

echo "wrote $out/Formula/docket.rb and $out/bucket/docket.json for $tag"
